import random

insults = [
    "You're so bad at cooking, you can't even make instant noodles.",
    "If there was a contest for laziness, you'd probably send someone else to enter for you.",
    "You have a face for radio... and a voice for silent movies.",
    "I'm not saying you're old, but your birth certificate is written in Roman numerals.",
    "You're so clumsy, you could trip over a cordless phone.",
    "If laughter is the best medicine, your face must be curing the world.",
    "You're so indecisive, I bet you can't even choose a favorite color.",
    "You're like a dictionary, you add meaning to my life.",
    "If being ugly was a crime, you'd be serving a life sentence.",
    "You're so bad at directions, you couldn't find water if you fell out of a boat.",
    "You're so forgetful, you probably forgot to read this insult.",
    "You're so slow, you make snails look like race cars.",
    "You're so short, you can't even see over a dandelion.",
    "You're so bad at singing, your voice could shatter glass... in a bad way.",
    "You're so bad at telling jokes, you make knock-knock jokes sound like Shakespeare.",
    "You're so clumsy, you could trip over a wireless network.",
    "You're so bad at math, you couldn't even count the number of insults in this list.",
    "You're so bad at dancing, you make a tree look like a professional dancer.",
    "You're so forgetful, you probably forgot your own name.",
    "You're so slow, you make sloths look like Olympic sprinters.",
    "You're so short, you could parachute off a curb.",
    "You're so bad at singing, you could make a deaf person cringe.",
    "You're so bad at telling jokes, you make dad jokes sound hilarious.",
    "You're so clumsy, you could trip over a thought.",
    "You're so bad at math, you couldn't even count to 10 with a calculator.",
    "You're so bad at dancing, you make a scarecrow look like a professional dancer.",
    "You're so forgetful, you probably forgot how to breathe.",
    "You're so slow, you make a snail on tranquilizers look fast.",
    "You're so short, you could bungee jump off a blade of grass.",
    "You're so bad at singing, you could make a deaf person run away.",
    "You're so bad at telling jokes, you make knock-knock jokes sound like stand-up comedy.",
    "You're so clumsy, you could trip over a virtual reality headset.",
    "You're so bad at math, you couldn't even count to 10 with a calculator and an abacus.",
    "You're so bad at dancing, you make a penguin look like a professional dancer.",
    "You're so forgetful, you probably forgot how to blink.",
    "You're so slow, you make a sloth on sedatives look speedy.",
    "You're so short, you could limbo under a garden gnome.",
    "You're so bad at singing, you could make a deaf person cry.",
    "You're so bad at telling jokes, you make knock-knock jokes sound like a comedy special.",
    "You're so clumsy, you could trip over your own shadow.",
    "You're so bad at math, you couldn't even count to 10 with a calculator, an abacus, and your fingers.",
    "You're so bad at dancing, you make a scarecrow look like a professional ballerina.",
    "You're so forgetful, you probably forgot how to swallow.",
    "You're so slow, you make a snail on sleeping pills look like Usain Bolt.",
    "You're so short, you could use a squirrel as a step ladder.",
    "You're so bad at singing, you could make a deaf person beg for silence.",
    "You're so bad at telling jokes, you make knock-knock jokes sound like a comedy masterpiece.",
    "You're so clumsy, you could trip over a thought and fall into a black hole.",
    "You're so bad at math, you couldn't even count to 10 with a calculator, an abacus, your fingers, and a supercomputer.",
    "You're so bad at dancing, you make a penguin look like a professional breakdancer.",
    "You're so forgetful, you probably forgot how to breathe... again.",
    "You're so slow, you make a sloth on sedatives look like a Formula 1 race car.",
    "You're so short, you could use a blade of grass as a limbo stick.",
    "You're so bad at singing, you could make a deaf person wish they were deaf.",
    "You're so bad at telling jokes, you make knock-knock jokes sound like a comedy revolution.",
    "You're so clumsy, you could trip over your own shadow... in the dark.",
    "You're so bad at math, you couldn't even count to 10 with a calculator, an abacus, your fingers, a supercomputer, and divine intervention.",
    "You're so bad at dancing, you make a scarecrow look like a professional salsa dancer.",
    "You're so forgetful, you probably forgot how to blink... permanently.",
    "You're so slow, you make a snail on sleeping pills look like a supersonic jet.",
    "You're so short, you could use a garden gnome as a basketball hoop.",
    "You're so bad at singing, you could make a deaf person wish they were mute.",
    "You're so bad at telling jokes, you make knock-knock jokes sound like a comedy revolution on steroids.",
    "You're so clumsy, you could trip over your own shadow... in broad daylight.",
    "You're so bad at math, you couldn't even count to 10 with a calculator, an abacus, your fingers, a supercomputer, divine intervention, and a miracle.",
    "You're so bad at dancing, you make a penguin look like a professional hip-hop dancer.",
    "You're so forgetful, you probably forgot how to swallow... your pride.",
    "You're so slow, you make a sloth on sedatives look like a warp-speed spaceship.",
    "You're so short, you could use a squirrel as a basketball.",
    "You're so bad at singing, you could make a deaf person wish they were blind.",
    "You're so bad at telling jokes, you make knock-knock jokes sound like a comedy revolution on steroids with fireworks.",
    "You're so clumsy, you could trip over your own shadow... and fall into a parallel universe.",
    "You're so bad at math, you couldn't even count to 10 with a calculator, an abacus, your fingers, a supercomputer, divine intervention, a miracle, and a time machine.",
    "You're so bad at dancing, you make a scarecrow look like a professional breakdancer on fire.",
    "You're so forgetful, you probably forgot how to blink... and breathe.",
    "You're so slow, you make a snail on sleeping pills look like a warp-speed spaceship on steroids.",
    "You're so short, you could use a garden gnome as a basketball hoop... in a dollhouse.",
    "You're so bad at singing, you could make a deaf person wish they were deaf... in both ears.",
    "youre so gay you make a rainbow look straight",
    "You're so bad at telling jokes, you make knock-knock jokes sound like a comedy revolution on steroids with fireworks and confetti."
    "wisdom has been chasing you for many years, but u have always been faster"
    
]

botinsults = [
    "stop talking, you dont bring anything worthwhile to the conversation",
    "you are the reason why people have trust issues",
    "you are a waste of oxygen",
    "you are a waste of time",
    "you are a waste of space",
    "you are a waste of life",
    "you are a waste of resources",
    "you are a waste of everything",]

emojiinsults = [
    "creep",
    "weirdo",
    "stop it",
    "for the love of god stop...",
    "youre creeping me out man",
    "stop this nonsense",
]
def get_insult():
    return random.choice(insults)

def get_bot_insult():
    return random.choice(botinsults)

def get_emoji_insult():
    return random.choice(emojiinsults)